# Generated by Django 5.0.7 on 2024-08-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='current_ip',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentmodel',
            name='last_connection',
            field=models.DateField(auto_now=True),
        ),
    ]
