# Generated by Django 5.0.7 on 2024-08-03 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_agentmodel_current_ip_agentmodel_last_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='current_ip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='group',
            field=models.ForeignKey(default='NoneGruop', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recursiveGroupModel', to='erp.modulemodel'),
        ),
        migrations.CreateModel(
            name='CodeFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('agentnumber', models.ForeignKey(default='NoneAgent', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='agentCode', to='erp.agentmodel')),
            ],
        ),
    ]
