# Generated by Django 5.0.7 on 2024-08-03 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_agentmodel_current_ip_alter_agentmodel_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='address',
            field=models.CharField(blank=True, default='NoneAddress', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agentmodel',
            name='dni',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='group',
            field=models.ForeignKey(default='NoneGroup', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recursiveGroupModel', to='erp.modulemodel'),
        ),
    ]
