# Generated by Django 5.0.7 on 2024-08-03 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_agentmodel_address_agentmodel_dni_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemodel',
            name='action',
        ),
        migrations.AddField(
            model_name='agentmodel',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='get',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulemodel',
            name='put',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursiveAgentModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
