# Generated by Django 5.0.7 on 2024-08-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_modulemodel_action_agentmodel_inactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.29c5bbc45c6c5p-15722', max_length=50, unique=True),
        ),
    ]
