# Generated by Django 5.0.7 on 2024-08-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_agentmodel_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.abce6210df0b0p-34871', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='codefree',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
