# Generated by Django 5.0.7 on 2024-08-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_agentmodel_secretkey_alter_codefree_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='last_connection',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.89ba6bb428714p-28085', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='modulemodel',
            name='register',
            field=models.DateField(auto_now_add=True),
        ),
    ]
