# Generated by Django 5.0.7 on 2024-08-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_agentmodel_current_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.ab2a898934788p-31010', max_length=50, unique=True),
        ),
    ]
