# Generated by Django 5.0.7 on 2024-08-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_agentmodel_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.e2734ad8b2954p-25029', max_length=50, unique=True),
        ),
    ]
