# Generated by Django 5.0.7 on 2024-08-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_agentmodel_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.bb08e7098362ap-19622', max_length=50, unique=True),
        ),
    ]
