# Generated by Django 5.0.7 on 2024-08-05 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_alter_agentmodel_secretkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursiveAgentModel', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='current_ip',
            field=models.CharField(default='0.0.0.0', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='group',
            field=models.ForeignKey(default='NoneGroup', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recursiveGroupModel', to='erp.modulemodel'),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.dcb0dfe49e9bep-14171', max_length=50, unique=True),
        ),
    ]
