# Generated by Django 5.0.7 on 2024-08-06 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_agentmodel_agent_alter_agentmodel_current_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.20922c5c0692cp-27533', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='codefree',
            name='agentnumber',
            field=models.ForeignKey(default='NoneAgent', on_delete=django.db.models.deletion.CASCADE, related_name='agentCode', to='erp.agentmodel'),
        ),
    ]
