# Generated by Django 5.0.7 on 2024-08-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_alter_agentmodel_secretkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursiveGroupModel', to='erp.modulemodel'),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.9852a8e36cdeep-26295', max_length=50, unique=True),
        ),
    ]
