# Generated by Django 5.0.7 on 2024-08-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_agentmodel_group_alter_agentmodel_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursiveGroupModel', to='erp.modulemodel'),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.ff43257127dbfp-13358', max_length=50, unique=True),
        ),
    ]
