# Generated by Django 5.0.7 on 2024-08-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_agentmodel_group_alter_agentmodel_secretkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='last_connection',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.334d7e6a955fap-13872', max_length=50, unique=True),
        ),
    ]
