# Generated by Django 5.0.7 on 2024-08-07 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_alter_agentmodel_last_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefree',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentmodel',
            name='secretKey',
            field=models.CharField(default='0x1.91329a752c113p-17058', max_length=50, unique=True),
        ),
    ]
